### ISSUE TITLE
Don't call methods in React Class 

### ISSUE THREAD

**Issue by MrEfrem** [mystor/meteor-routecore#14]
upConter don't call by click button
```
/** @jsx React.DOM */
var layout = React.createClass({
    upCounter: function(e){
        console.log(1);
    },
    render: function(){
        return (
            <div>
                <h1>Welcome to Meteor!</h1>

                <button onclick={this.upCounter}>Click Me</button>
            </div>
            );
    }
});

RouteCore.map(function () {
    var home = this.route('/', layout);
});]]
```

**Comment by mystor** [comment]
Try changing the property name from `onclick` to `onClick`. Javascript (any by extension JSX) is case-sensitive.

**Comment by MrEfrem** [comment]
Thanks for the help. And onClick inner blazeComponent won't work?

**Comment by mystor** [comment]
I'm not sure what you mean by that. I don't think you can add event handlers to BlazeComponents, but inside the blaze component you can have click handlers in the normal Meteor way.

**Comment by MrEfrem** [comment]
Thanks for the help.
