### ISSUE TITLE
Clients generating identical session values as server.

### ISSUE THREAD

**Issue by trusktr** [mystor/meteor-routecore#18]
In the README, it says

> NOTE RouteCore does not send the session values which are generated on the server to the client. When the client renders code for the first time, it is expected that it will generate identical session values.

Can you explain this a little more? Is there some handling that we need to implement? Or is this already handled if we stick to the API?

**Comment by mystor** [comment]
Basically, if you don't do anything weird it should work fine. It just means that changes made to session state on the server during server side rendering aren't propagated to the client, but as the exact same code is called in the client on load, it shouldn't matter.

**Comment by trusktr** [comment]
Alright, thanks!
