### ISSUE TITLE
Modularizing code

### ISSUE THREAD

**Issue by trusktr** [mystor/meteor-routecore#22]
How would we split app.jsx into separate files (i.e. import React classes that are exported from other files)?

**Comment by mystor** [comment]
If you make the classes global, they will be visible in other files. This is pretty standard meteor global variable stuff.

**Comment by trusktr** [comment]
For sure. I'd like to modularize if possible, like one does with CommonJS modules of ES6 modules. Can Meteor Packages be used in the same way? For a large application, can we separate React classes into separate "packages"? Would it be practical?

**Comment by mystor** [comment]
Routecore doesn't do anything special to help with modularizing your meteor
projects. If you want to do that, look into other mechanisms which meteor
can help you with.

**Comment by trusktr** [comment]
Do the load order rules found at http://docs.meteor.com/#/full/fileloadorder apply in the same way to the `.jsx` files?

**Comment by mystor** [comment]
Yup

**Comment by trusktr** [comment]
Sweet. So I'll just follow the standard practices of Meteor packaging. I'm basically thinking of using this guideline: http://tech.exponential.io/meteor/building-large-modular-apps-meteor/, except with jsx files instead of js files.
